num1 = int(input("Enter the first integer: "))
num2 = int(input("Enter the second integer: "))
num3 = int(input("Enter the third integer: "))
sum_of_numbers  = (num1 + num2 +num3)
product_of_numbers = (num1 * num2 * num3)
average_of_numbers = (sum_of_numbers/3)
print("The sum of the numbers:", (sum_of_numbers))
print("The product of the numbers:", (product_of_numbers))
print("The average of the numbers:", (average_of_numbers))