length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))
perimeter = (length * 2 + width *2)
area = (length) * (width)
print("The perimeter of the rectangle is", (perimeter))
print("The area of the rectangle is", (area))